name: openvpn
services:

  openvpn-supereasy:
    image: julman99/openvpn-supereasy
    container_name: openvpn-supereasy
    cap_add:
      - NET_ADMIN
    environment:
      - OPENVPN_EXTERNAL_HOSTNAME=some.domain
      - OPENVPN_PORT_UDP=1194 #or 'off' if no udp support is desired
      - OPENVPN_PORT_TCP=445 #or 'off' if no tcp support is desired
      - OPENVPN_DNS=94.140.14.14 #DNS to be used by clients when routed through this vpn (I've used AdGuard DNS [dns.adguard.com] here, but you can use any DNS server you like)
      - OPENVPN_CLIENTS=hlabsPC hlabsPixel hlabsTablet sweetPixel hlabsHp halbsTest #optional, space separated list of clients to be created. If not set, no clients are created
      - OPENVPN_PING=10 #optional, ping interval to keep connections alive
      - OPENVPN_PING_RESTART=60 #optional, restart connection if no ping has been sucessful for the specified time
      # - OPENVPN_CIPHER=some.cipher #optional, one of AES-256-GCM, AES-128-GCM, AES-256-CBC or AES-128-CBC. If ommited OpenVPN tries to negotiate the most secure cipher supported by both server and client
      - OPENVPN_FASTIO=0 #optional, enable fastio on the server
      - OPENVPN_NETWORK_UDP=0 #optional, network that will be used for clients conneting through udp. Defaults to 10.8.0.0/24
      - OPENVPN_NETWORK_TCP=0 #optional, network that will be used for clients conneting through tcp. Defaults to 10.9.0.0/24
      # - OPENVPN_ROUTE_DEV=0 #optional, device to route traffic, this parameter is useful when running openvpn with host networking
      - OPENVPN_TUN_MTU=1420 #optional, change mtu size. Defaults to 1420
      - OPENVPN_MSSFIX=1380 #optional, enables MSS fixing. Set to 0 for automatic or a specific value like 1400. If not set, MSS fixing is disabled. It is recommended to set it to 40 bytes less than OPENVPN_TUN_MTU
      - TZ=Africa/Abidjan #optional timezone
    volumes:
      - ./server:/etc/openvpn/server
      - ./clients:/etc/openvpn/clients
    ports:
      - 1194:1194/udp
      - 445:445/tcp
    restart: unless-stopped
