name: openvpn
services:
  openvpn-supereasy:
    image: julman99/openvpn-supereasy
    container_name: openvpn-supereasy
    cap_add:
      - NET_ADMIN
    env_file:
      - .env.openvpn
    volumes:
      - ./server:/etc/openvpn/server
      - ./clients:/etc/openvpn/clients
    ports:
      - 1194:1194/udp
      - 1443:1443/tcp  # Nouveau port TCP sécurisé
    restart: unless-stopped
    # Ajout de sysctls pour optimiser le réseau
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.forwarding=1
    # Politique de redémarrage améliorée
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3